# Generated by Django 6.0.3 on 2026-03-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
    ]
