# Generated by Django 6.0.3 on 2026-04-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contact'),
    ]

    operations = []
