# Generated by Django 6.0.3 on 2026-04-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
