# Generated by Django 6.0.3 on 2026-06-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_galleryimage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['-created_at'], name='contact_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created_at'], name='feedback_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['is_active', 'display_order', '-created_at'], name='gallery_active_order_idx'),
        ),
    ]
